import React from 'react'
import Contact from './Contact';

const Contactadata = () => {
    const jobData = [
        {
          title: 'KITCHEN HELPER',
          company: 'Delishlicks',
          datePosted: '19/06/2024',
          location: 'Slave Lake, ABT0G 2A3',
          salary: '$15.40 hourly / 35 to 40 hours per Week',
          employmentType: 'Permanent employment / Full time',
          schedule: 'Day, Evening, Morning, Shift, Weekend',
          startDate: 'Starts as soon as possible',
          benefits: 'Health benefits',
          vacancies: 2,
          languages: 'English',
          education: 'No specific education requirements mentioned.',
        },
        {
          title: 'FRONT OF HOUSE STAFF',
          company: 'The Cozy Cafe',
          datePosted: '25/06/2024',
          location: 'Downtown Ludhiana, Punjab',
          salary: '₹18,000 - ₹25,000 per month',
          employmentType: 'Full-time',
          schedule: 'Flexible shifts',
          startDate: 'July 15, 2024',
          benefits: 'Paid time off, staff discounts',
          vacancies: 4,
          languages: 'English, Punjabi preferred',
          education: 'High school diploma or equivalent',
        },
        {
          title: 'DELIVERY DRIVER',
          company: 'Speedy Eats',
          datePosted: '01/07/2024',
          location: 'Various locations in Ludhiana',
          salary: '₹150 - ₹200 per delivery + incentives',
          employmentType: 'Part-time or Full-time',
          schedule: 'Morning, Evening, Weekend',
          startDate: 'Immediate',
          benefits: 'Fuel allowance',
          vacancies: 3,
          languages: 'Punjabi, Hindi',
          education: 'Valid driver\'s license',
        },
        {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'KITCHEN HELPER',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
      ];
    
  return (
    <div>
      <div>
        <Contact jobs={jobData} />
      </div>
    </div>
  )
}

export default Contactadata
