import React from 'react'
import Contact from './Contact';

const Contactadata = () => {
    const jobData = [
        {
          title: 'Kitchen Helper',
          company: 'Delishlicks',
          datePosted: '19/06/2024',
          location: 'Slave Lake, ABT0G 2A3',
          salary: '$15.40 hourly / 35 to 40 hours per Week',
          employmentType: 'Permanent employment / Full time',
          schedule: 'Day, Evening, Morning, Shift, Weekend',
          startDate: 'Starts as soon as possible',
          benefits: 'Health benefits',
          vacancies: 2,
          languages: 'English',
          education: 'No specific education requirements mentioned.',
        },
        {
          title: 'Front of House Staff',
          company: 'The Cozy Cafe',
          datePosted: '25/06/2024',
          location: 'Downtown Ludhiana, Punjab',
          salary: '₹18,000 - ₹25,000 per month',
          employmentType: 'Full-time',
          schedule: 'Flexible shifts',
          startDate: 'July 15, 2024',
          benefits: 'Paid time off, staff discounts',
          vacancies: 4,
          languages: 'English, Punjabi preferred',
          education: 'High school diploma or equivalent',
        },
        {
          title: 'Delivery Driver',
          company: 'Speedy Eats',
          datePosted: '01/07/2024',
          location: 'Various locations in Ludhiana',
          salary: '₹150 - ₹200 per delivery + incentives',
          employmentType: 'Part-time or Full-time',
          schedule: 'Morning, Evening, Weekend',
          startDate: 'Immediate',
          benefits: 'Fuel allowance',
          vacancies: 3,
          languages: 'Punjabi, Hindi',
          education: 'Valid driver\'s license',
        },
        {
          "title": "Restaurant Manager",
          "company": "The Cozy Bistro",
          "datePosted": "25/07/2024",
          "location": "Calgary, ABT2P 2Y7",
          "salary": "$55,000 - $70,000 per year",
          "employmentType": "Permanent employment / Full time",
          "schedule": "Flexible, including evenings and weekends",
          "startDate": "August 15, 2024",
          "benefits": "Paid vacation, Health and dental insurance, Performance bonuses",
          "vacancies": 1,
          "languages": "English",
          "education": "Bachelor's degree in Hospitality Management or related field preferred",
          "experience": "Minimum 3 years of experience in restaurant management"
        },
        {
          "title": "Oragnic market garden worker",
          "company": "Green Earth Farms",
          "datePosted": "10/08/2024",
          "location": "Edmonton, ABT5L 4X1",
          "salary": "$17.50 hourly / 40 hours per Week",
          "employmentType": "Seasonal / Full time",
          "schedule": "Daytime, Monday to Friday, some weekends may be required",
          "startDate": "September 1, 2024",
          "benefits": "Farm produce",
          "vacancies": 4,
          "languages": "English (asset)",
          "education": "No specific education requirements mentioned, experience in agriculture is an asset",
          "responsibilities": [
            "Planting and harvesting vegetables",
            "Weeding and soil maintenance",
            "Assisting with market sales",
            "General farm duties"
          ]
        },
        {
          "title": "Organic Farm Worker",
          "company": "Prairie Roots Organics",
          "datePosted": "01/08/2024",
          "location": "Saskatoon, SKS7K 3J5",
          "salary": "$16.00 - $19.00 hourly / 30-40 hours per week",
          "employmentType": "Contract / Full time (potential for permanent)",
          "schedule": "Flexible, primarily daytime",
          "startDate": "September 15, 2024",
          "benefits": "Opportunity for advancement, Learning about sustainable agriculture",
          "vacancies": 3,
          "languages": "English",
          "education": "High school diploma or equivalent, interest in organic farming",
          "skills": [
            "Ability to work outdoors in various weather conditions",
            "Physical stamina",
            "Teamwork",
            "Attention to detail"
          ]
        },
        {
          "title": "Organic Vegetable Farming Assistant",
          "company": "Prairie Roots Organics",
          "datePosted": "01/08/2024",
          "location": "Saskatoon, SKS7K 3J5",
          "salary": "$16.00 - $19.00 hourly / 30-40 hours per week",
          "employmentType": "Contract / Full time (potential for permanent)",
          "schedule": "Flexible, primarily daytime",
          "startDate": "September 15, 2024",
          "benefits": "Opportunity for advancement, Learning about sustainable agriculture",
          "vacancies": 3,
          "languages": "English",
          "education": "High school diploma or equivalent, interest in organic farming",
          "skills": [
            "Ability to work outdoors in various weather conditions",
            "Physical stamina",
            "Teamwork",
            "Attention to detail"
          ]
        },
        {
          "title": "Farm Hand - Organic Dairy",
          "company": "Happy Cows Dairy",
          "datePosted": "15/07/2024",
          "location": "Regina, S4P 3A3",
          "salary": "$17.00 hourly / 40 hours per week",
          "employmentType": "Permanent employment / Full time",
          "schedule": "Morning, Day, some weekends",
          "startDate": "August 1, 2024",
          "benefits": "Accommodation on-site (optional), Paid time off",
          "vacancies": 1,
          "languages": "English",
          "education": "No specific education requirements mentioned, experience with livestock an asset",
          "responsibilities": [
            "Feeding and caring for dairy cows",
            "Milking duties",
            "Maintaining barn cleanliness",
            "General farm maintenance"
          ]
        },
        {
          "title": "Market Garden Manager",
          "company": "Sunnyside Produce",
          "datePosted": "22/07/2024",
          "location": "Moose Jaw, S6H 4P1",
          "salary": "$45,000 - $55,000 per year",
          "employmentType": "Permanent employment / Full time",
          "schedule": "Flexible, including weekends for market days",
          "startDate": "September 1, 2024",
          "benefits": "Health benefits, Paid vacation, Profit sharing",
          "vacancies": 1,
          "languages": "English",
          "education": "Diploma or degree in Agriculture or Horticulture preferred",
          "experience": "Minimum 2 years experience in market gardening",
          "skills": [
            "Crop planning and management",
            "Soil health management",
            "Pest and disease control (organic methods)",
            "Sales and marketing"
          ]
        },
        {
          "title": "Seasonal Farm Worker",
          "company": "Harvest Bounty Farms",
          "datePosted": "28/07/2024",
          "location": "Swift Current, S9H 3X5",
          "salary": "$15.50 hourly / 30-40 hours per week",
          "employmentType": "Seasonal / Full time",
          "schedule": "Daytime, Monday to Friday",
          "startDate": "August 15, 2024",
          "benefits": "None mentioned",
          "vacancies": 5,
          "languages": "English (asset)",
          "education": "No specific education requirements mentioned",
          "responsibilities": [
            "Harvesting various crops",
            "Sorting and packing produce",
            "Field work as required"
          ]
        },
        {
            title: 'Lower mainland BC',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'BC local food and the farming',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'Organic vegetable farming',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'Food counter supervisor',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'Food counter attendant',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'Need the basic education qualification.',
          },
          {
            title: 'Cook job',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'Need the graduation in this field.',
          },
          {
            title: 'Kitchen helper',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
          {
            title: 'Kitchen manager',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'Need the graduuation in the particular field.',
          },
          {
            title:'Organic vegetable farming',
            company: 'Delishlicks',
            datePosted: '19/06/2024',
            location: 'Slave Lake, ABT0G 2A3',
            salary: '$15.40 hourly / 35 to 40 hours per Week',
            employmentType: 'Permanent employment / Full time',
            schedule: 'Day, Evening, Morning, Shift, Weekend',
            startDate: 'Starts as soon as possible',
            benefits: 'Health benefits',
            vacancies: 2,
            languages: 'English',
            education: 'No specific education requirements mentioned.',
          },
      ];
    
  return (
    <div>
      <div>
        <Contact jobs={jobData} />
      </div>
    </div>
  )
}

export default Contactadata
